### ISSUE TITLE
Leverage Port Library in compiler technology

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1642]
Leverage the features in the OMR port library within the OMR compiler technology.  This affords a number of advantages, including:

* utilize a consistent API for accessing platform and OS features
* remove duplicated functionality within compiler and port library that should more naturally live in the port library
* reap RAS and tooling benefits provided by port library with no additional effort

Discussion around exploiting the port library in the compiler, including more discussion around the pros and cons, occurred in issue #589.

Compiler technology includes JitBuilder and compiler tests as well.

This Issue represents the umbrella epic task for this work.  Sub-tasks:

- [ ] create a port library build dependence when OMR compiler technology is built
- [ ] ensure port library is initialized early in OMR initialization so that it is ready to be used as early as possible by the compiler technology
- [ ] use PID function from port library
- [ ] use `J9OSMutex` in `TR::Monitor`

**Comment by 0xdaryl** [comment]
@nbhuiyan @rwy0717

**Comment by dibyendumajumdar** [comment]
Hi - not sure if this is the right place to raise this. I noticed while attempting to create a cutdown version of OMR containing only the compiler related component that https://github.com/eclipse/omr/blob/master/compiler/control/CompileMethod.cpp includes the header file 'omr.h'. I wasn't able to see why this was needed. 

I think the compiler layer should avoid accessing stuff from upper layers so that a proper separation of concerns is maintained. In particular including a top level header fle such as 'omr.h' can result in a lot of unexpected dependencies. 

Regards

**Comment by nbhuiyan** [comment]
@dibyendumajumdar 
Thank you for highlighting that. As far as I could tell, omr.h was unnecessary in CompileMethod.cpp as well as one other location within the compiler. The following PR would fix that: #2615

**Comment by dibyendumajumdar** [comment]
Great, thank you.
