### ISSUE TITLE
Create the opcodes `breturn`, `bureturn` and evaluators

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1887]
Based on discussion in #1842, it seems that to help raise `Int8` to a first class citizen, the right answer is to implement `breturn and `bureturn` to be used in functions expected to return an `Int8`

This task should involve: 

- [ ] Add the opcodes to the OpCode enum, 
- [ ] Fill in the opcode properties table for them.
- [ ] Change the implementation of `OMR::ILOpCode::returnOpCode()` to use `breturn`. 
- [ ] Add an evaluator for X
- [ ] Add an evaluator for P
- [ ] Add an evaluator for Z
- [ ] Add an evaluator for ARM
- [ ] Add test cases to exercise the new opcode and evaluator.

**Comment by mgaudet** [comment]
Closing this for now, pending a discussion in #1901

**Comment by mgaudet** [comment]
Reopening based on discussion in #1901
