### ISSUE TITLE
Create the opcode `sreturn` and evaluators

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1888]
Based on discussion in #1842, it seems that to help raise `Int16` to a first class citizen, the right answer is to implement `sreturn` and use it for functions expected to return an `Int16`

This task should involve: 

- [ ] Add the opcode to the OpCode enum, 
- [ ] Fill in the opcode properties table for it.
- [ ] Change the implementation of `OMR::ILOpCode::returnOpCode()` to use it. 
- [ ] Add an evaluator for X
- [ ] Add an evaluator for P
- [ ] Add an evaluator for Z
- [ ] Add an evaluator for ARM
- [ ] Add test cases to exercise the new opcode and evaluator.

**Comment by mgaudet** [comment]
Closing this for now, pending a discussion in #1901

**Comment by mgaudet** [comment]
Reopening based on the discussion in #1901
