### ISSUE TITLE
Remove VMThread reclamation logic

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2256]
The deprecated VMThread reclamation logic will be removed from the Eclipse OMR compiler.  This is logic that was introduced by OpenJ9 many years ago to re-use the register normally reserved for the J9VMThread in areas of high register pressure. If the compiler can prove that the VMThread is not needed in a context where registers are required to avoid spilling then it may spill the VMThread register to free it for general register assignment. There is also logic to use the VMThread register in a GRA context, as well as a late tree-lowering pass (late edge splitting) to help with reclamation placement.

This is technology that was only ever enabled on 32-bit Windows for OpenJ9 and saw limited performance gains.  It has since been disabled (via #2241) in preparation for its removal.

The only known downstream project that has a dependency on this feature is OpenJ9, and the work in this issue will be staged with corresponding PRs in OpenJ9 to ensure all parts are removed with minimal disruption.

This is the umbrella epic to track all the removal work in Eclipse OMR.  This work includes, but is not expected to be limited to, the following:

- [x] disable VMThread reclamation (#2241)
- [ ] remove VMThread enablement queries and fold surrounding code
- [ ] remove VMThread GRA optimization and from lowerTrees
- [ ] remove late edge splitting optimization
- [ ] remove VMThread preservation/restoration/spill placement logic in CodeGenerator
- [ ] remove all `isVMThreadRequired`
- [ ] remove VMThread infrastructure in CodeGenerator
