### ISSUE TITLE
Compiled body metadata

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2369]
Provide the means to associate and manage metadata with a compiled body.  Metadata is useful for a variety of purposes including:

* describing address ranges of compiled bodies (e.g., given a PC, determine which compiled body it belongs to), or address ranges within a compiled body (e.g., to delimit methods that have been inlined into a compiled body)
* associating information with certain PC offsets within a method (e.g., location of patchable guard sites, interpreter stack or PC adjustments that must be done prior to calling into the interpreter from compiled code, etc.)
* GC maps to describe which stack slots and registers contain live references that could be modified by a garbage collector

Some basic infrastructure to support compiled body metadata was already committed to Eclipse OMR based on similar support in OpenJ9.  This includes a code metadata manager (`runtime/OMRCodeMetaData.[ch]pp`) for maintaining and querying metadata in an AVL structure.  However, it is not currently used or exercised.

The general tasks involved:

- [ ] Decide on whether `runtime/OMRCodeMetaDataPOD.hpp` or `runtime/OMRCodeMetaData.hpp` shall be the extensible, elemental component for describing metadata associated with a compiled body.  Whichever is not used should be deleted to avoid confusion.
- [ ] Decide what should be the most fundamental entities associated with code metadata.  For example, the start and end PCs of the compiled body along with the optimization level it was compiled at.  Incorporate those in the OMR elemental component.
- [ ] Review the functionality provided in `runtime/OMRCodeMetaDataManager.[ch]pp` to ensure querying, insertion, deletion functionality is robust enough and can function in the presence of multiple code caches and compilation threads.
- [ ] Resurrect and enable PR #832 which adds compiler tests around the code metadata framework.  It was reverted because it uses C++ syntax that is not supported on all build compilers.  As written, PR #832 uses C++ range-based loops which are supported starting with gcc 4.6 (not gcc 4.4 which is what this technology is built with), so the code will have to be adapted to not use range-based loops.
- [ ] Provide the means for collecting and publishing metadata for a compiled body after the compilation is finished (should that be desired for a particular language runtime).
