### ISSUE TITLE
Remove deprecated unsigned IL opcodes

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2657]
The majority of unsigned opcodes have been deprecated and can be removed with care.  In the majority of cases the generic IL opcode performs exactly the same operation.  Some IL operations that do care about the signed-ness of an opcode will remain.

The categorized list of IL opcodes to remove from OMR follows.  This epic will track the removal of those opcodes.  I suggest a separate PR per category.

| Operation | IL OpCode |
| :---- | :---- |
Equality compare | `bucmpeq` `bucmpne` `iucmpeq` `iucmpne` `lucmpeq` `lucmpne` `sucmpeq` `sucmpne`
Equality compare and branch | `ifiucmpeq` `ifiucmpne` `iflucmpeq` `iflucmpne` `ifbucmpeq` `ifbucmpne` `ifsucmpeq` `ifsucmpne`
Constant | `buconst` `iuconst` `luconst` `cconst`
Load | `buload` `buloadi` `cload` `cloadi` `iuload` `iuloadi` `iuRegLoad` `luload` `luloadi` `luRegLoad`
Store | `bustore` `bustorei` `cstore` `cstorei` `iuRegStore` `iustore` `iustorei` `luRegStore` `lustore` `lustorei`
Call/Return | `iucall` `iucalli` `iureturn` `lucall` `lucalli` `lureturn`
Add/Subtract | `aiuadd` `aluadd` `buadd` `busub` `cadd` `csub` `iuadd` `iuneg` `iusub` `luadd` `luneg` `lusub`
Multiply | `iumul` `cmul`
Ternary | `buternary` `iuternary` `luternary` `suternary`
Shift | `cshl` `iushl` `lushl`
Shift Logical | `ishfl` `lshfl` `iushfl` `lushfl` `bshfl` `sshfl` `bushfl` `sushfl`

**Comment by 0xdaryl** [comment]
@jdmpapin , would you mind vetting this list to see if anything doesn't belong here?  Thanks.

**Comment by jdmpapin** [comment]
Signedness should affect the range of inputs for which the conversions from floating-point to integer are "particularly sensible," e.g. `f2b` would naturally expect inputs that round to integers in [-128, 128), but `f2bu` would expect [0, 256). In the context of IL, I'm not sure what the results are supposed to be for inputs outside these ranges. One possibility is to map negative inputs as though the result is signed, and large positive inputs as though the result is unsigned, so that e.g.

    f2b(-1.0) == f2b(255.0) == 0xff

This way only one opcode would be necessary. However, this strategy may not map cleanly to hardware. Considering `f2i[u]`, it looks like instructions tend to care about signedness, and that they'll do things like trap or saturate, e.g. x86's `cvtss2si` (signed), and Power's `fctiw` (signed) and `fctiwu` (unsigned).

So the narrowing conversions from floating-point to integer probably don't belong on this list.

There are a few conspicuous absences as well:

A number of the 16-bit unsigned opcodes are named not with `su`, but rather `c` for Java's unsigned `char`, e.g. `cconst`, `cload[i]`, `cstore[i]`, `cadd`, `csub`, `f2c`, `d2c`.

The low half of the product of two integers is insensitive to signedness, so `iumul` is also unnecessary.

**Comment by Leonardo2718** [comment]
Regarding floating-point to integer conversions, there was some discussion about this in #2375.

**Comment by 0xdaryl** [comment]
Repeating a nice explanation from @andrewcraik from #3450 on the unsigned multiply opcodes here:

> So given that multiplication is repeated addition the signed-ness of the operand types does not affect the low half of the result. So an `imul` applies to both signed and unsigned integers because the result produces is the low 32-bits and behavior on overflow is undefined. We have an `imulh` and an `iumulh` to represent the high half of a 32bit multiply which does vary based on signedness. As a result, the `iumul` is deprecated as is `iuadd` et al. The same principle applies to `lmul`. This means that `lmul` is signless and we need an `lmulh` and `lumulh` if we don't already have them. If you care about overflow the signed ness of the operation is implicit in the use of either `OverflowCHK` or `UnsignedOverflowCHK` but the overflow check evaluators generally need to specially handle the evaluation of their children to ensure that they test the correct flags etc. As a result I don't think adding an `lumul` is appropriate.

**Comment by 0xdaryl** [comment]
@jdmpapin : I updated the table above with your feedback.  Thanks.

**Comment by andrewcraik** [comment]
conversions generally care about signedness and I agree with @jdmpapin that the float to int conversions are probably needed. What happens for an out of range value I would expect to be undefined behavior. If you want specific semantics then I would posit that you should have an `OverflowCHK` or `UnsignedOverflowCHK` treetop to denote that you want a trap and then you need a handler that will do the semantics you expect for an out of range value since that behavior will vary.

I also agree that `c` versions of opcodes which are an alternative naming for `su` means that they either need to be renamed (if being kept) or removed.

I would also note that removal of the opcode should include cleaning up the optimizer of code to handle the cases. Care will need to be taken to check for code based on capability queries where the operation being removed is sign agnostic (eg if there is an add handler that checks for isUnsigned or something like that). Reducing dead code goes a long way to aiding comprehension and maintainability.

**Comment by 0xdaryl** [comment]
For opcodes that affect Switch Analyzer, see #3983.

**Comment by wbh123456** [comment]
Side Tasks To-do List:

- [ ] Function `bool OMR::Node::isTernaryHigh()` will always return false after removing `Add/Sub` unsigned opcodes. Therefore, should fold this function. But be CAUTION that this function is also referenced in the OpenJ9.

- [ ] Function `static TR::ILOpCodes unsignedSubtractOpCode(TR::DataType type)` should also be removed as all unsigned sub opcode for this datatype should have been deprecated.

**Comment by wbh123456** [comment]
To-do List:

- [ ] Investigate on and remove `TR::ifsucmpne` and `TR::ifsucmpeq` in `OMRsimpifierHandlers.cpp` . It is passed as an argument to a function that is not removable. Should replace the opcode with another compatible opcode.

- [ ] Investigate on and remove `TR::cconst` in `OMRsimpifierHandlers.cpp` . See description above.

**Comment by wbh123456** [comment]
There is no reference to any opcodes in the `Shift Logical` category.

**Comment by wbh123456** [comment]
- Clean up references of the deprecated opcodes from OpenJ9 --> eclipse/openj9#6465 (OPEN)
    - Remove remnants of `luadd` / `lusub` --> eclipse/openj9#7004 (OPEN)
- Clean up references of the deprecated opcodes from OMR:
    - Equality compare --> #3970 (MERGED)
    - Equality compare and branch -->#3970  (MERGED)
    - Constant --> #4033 (OPEN)
    - Load --> #4092 (OPEN)
    - Store --> #4113 (OPEN)
    - Call/Return --> #4094 (MERGED)
    - Add/Subtract --> #4096 (REVERTED in #4126)
    - Multiply --> #4115 (MERGED)
    - Ternary --> #4115 (MERGED)
    - Shift --> #4116 (MERGED)
    - Shift Logical --> No references in this category

**Comment by wbh123456** [comment]
_In my first attempt of removing deprecated IL opcodes, I did not separate and organize my PRs 
properly. This made the commits hard to review and caused bad compiler behavior that were hard to debug (e.g. https://github.com/eclipse/openj9/pull/6465#discussion_r321876165)._
_Therefore, I am going to re-factor and track the rest of my PRs in a safer and clearer way. The following is a list of steps I am going to take to remove deprecated unsigned opcodes:_

## Steps to Remove Deprecated Unsigned IL Opcodes:
### 1. Add any pattern recognition support for removing unsigned opcodes:

TBD

### 2. Clean up creations of nodes with deprecated unsigned opcodes and using `TR_ASSERT_FATAL` to preventing them from being created in the future:

TBD

### 3. Clean up all references to the deprecated opcodes:

TBD
