### ISSUE TITLE
Replace TR_Method identity checks

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#3766]
Replace the method identity checks from `TR_Method` with proper capability queries:

- [ ] Remove `methodType` checks from `ras/Limitfile.cpp`
   - [ ] Introduce `OMRVMMethodEnv.cpp`(#3765)
   - [ ] Introduce `OMRVMMethodEnv.cpp` to downstream project makefiles.  In OpenJ9, introduce an implementation of `tokenizeSignature` from the logic in `methodSigCanBeFound`.
   - [ ] Add implementation of `tokenizeSignature` to OMRVMMethodEnv and call from `ras/Limitfile.cpp`
   - [ ] Clean up OMR APIs to `methodSigCanBeCompiled` (and related functions) to avoid passing in the type of method
- [ ] Allow VP `constrainACall` to be specialized by project
   - [ ] Create virtual `innerConstrainACall` (#3763)
   - [ ] Create virtual `innerConstrainACall` in OpenJ9 and relocate implementation and support functions to OpenJ9
   - [ ] Delete `innerConstrainACall` from OMR
- [ ] Remove VP `getParmValues` (#3761)
- [ ] Find and implement an appropriate capability query for
https://github.com/eclipse/omr/blob/8e68248e56ef846faa07257d5c498a05664a50e3/compiler/z/codegen/SystemLinkage.cpp#L694
@fjeremic, I'd like your advice on this one.
- [ ] Remove `methodType` identity from `TR_Method`

**Comment by fjeremic** [comment]
>  Find and implement an appropriate capability query for
> 
> [omr/compiler/z/codegen/SystemLinkage.cpp](https://github.com/eclipse/omr/blob/8e68248e56ef846faa07257d5c498a05664a50e3/compiler/z/codegen/SystemLinkage.cpp#L694)
> 
> Line 694 in [8e68248](/eclipse/omr/commit/8e68248e56ef846faa07257d5c498a05664a50e3)

I'll mostly be handling this one in an upcoming PR. The `if` portion should remain and the `else` portion migrated to OpenJ9.
