### ISSUE TITLE
Permanently enable the OMR_GC_ARRAYLETS and OMR_GC_HYBRID_ARRAYLETS flags

### ISSUE THREAD

**Issue by rwy0717** [eclipse/omr#3989]
Hybrid arraylets are becoming non-optional in OMR. Arraylets are a discontiguous representation of arrays on the OMR heap. Arraylets are important for region based collectors, where the total size of an array is larger than the maximum object size.

Hybrid arraylets are a minor variant of the standard arraylets:
> Effectively Hybrid arraylets let arraylets and none arraylet arrays co-exist in the runtime without having to check the array type but rather rely on the array length.

For a while we've expected hybrid arraylets to be enabled by downstream projects, now we're just making it official.

To do:
- [X] Turn on both flags by default (#3981)
- [x] Disable compile options, leaving both flags permanently on (#3994)
- [x] Remove OMR_GC_HYBRID_ARRAYLETS ifdefs (#3988)
- [x] Remove OMR_GC_ARRAYLETS ifdefs (#4131)
- [x] Remove both flags from the OMR build system (#4291)

**Comment by rwy0717** [comment]
project completed.
