### ISSUE TITLE
Improve conceptual integrity of Method hierarchy

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#4047]
This epic is a placeholder for changes to improve the overall conceptual integrity of the Method hierarchy.  This is the hierarchy derived from and including the base `TR_Method` class.  It will include structural, API, and documentation changes.

This is not an exhaustive list, but rather a starter set of tasks.  Consultation will occur along the way.

- [ ] Make the `TR_Method` base class an extensible class to isolate obvious project functionality
   - [ ] Replace uses of `TR_Method` with `TR::Method` typedef in OMR and downstream
   - [ ] Create Method extensible class and concrete class
   - [ ] Relocate OpenJ9-specific functions to OpenJ9 specialization
- [ ] Replace Method identity checks with capability checks (#3766)
- [ ] Create a MethodSignature class to encapsulate the naming of a method and operations (e.g., comparison, printing)
- [ ] Method hierarchy conceptual integrity
   - [ ] Reconcile meaning of `TR_ResolvedMethod` and `TR::ResolvedMethod`
- [ ] Document the API in the hierarchy
