### ISSUE TITLE
Port JITServer to Z

### ISSUE THREAD

**Issue by dchopra001** [eclipse/omr#4463]
As part of the work being tracked in https://github.com/eclipse/openj9/issues/6914, there are some changes that need to be made in the OMR project.

I have broken the changes into logical PRs below. We can discuss any broader issues or individual issues here or within the PRs themselves. Most of the changes boil down to adding a `comp->isOutOfProcessCompilation()` check. Since OMR is not aware of this query, I have made all PRs with this check a draft so that no testing is run until we can decide on what we should replace each query with.

Where possible, I have used an already available front-end query instead of the above check. I will take another pass through the PRs tomorrow to make sure I haven't missed anything.

- [x] Use FE query to add relocations for TR_HelperAddress: #4454
- [x] Add method to reset SupportsArrayTranslateTRxx flags: #4455
- [x] Use CG query to check for guard merging support: #4456
- [x] Improve relocation record checks inside genLoadLongConstant: #4457
- [x] Improve relocation record checks and avoid generating PC relative instructions for JITServer: #4458
- [x] Create TR_MethodCallAddress relocation for resolved methods: #4459
- [x] ~Don't add relocations for TR_ConstantPools in JITServer mode: #4460~
- [x] Add relocation record for TR_DataAddress in JITServer: #4461
- [x] Add relocation records correctly inside ConstantDataSnippets: #4462
- [x] Remove some statics from z/codegen: #5226
- [x] Add new callUsesHelperImplementation: #5463
- [x] Use Snippet to load methodPointer in remote compile: #5518

Other work needed to enable JITServer Support (CPU detection and cleanup):
- [x] Remove TR::S390JNICallDataSnippet references: #5233
- [x] Remove S390JNICallDataSnippet class: #5257
- [x] Remove uses of CPU::Architecture enum in OMRInstOpCodeProperties: #5459
- [x] Revert change to OMR::CPU(): #5475
- [x] Deprecate uses of getSupportsArch in Z codegen: #5504
- [x] Explicitly specify target in Compilation constructor: #5506

**Comment by dchopra001** [comment]
@fjeremic @mpirvu FYI

**Comment by dchopra001** [comment]
@Leonardo2718 FYI

**Comment by mpirvu** [comment]
@dchopra001 Any new developments on the Z omr port?

**Comment by fjeremic** [comment]
Removing stale label on this one and adding it to the backlog as it is something actively being worked on.

**Comment by dchopra001** [comment]
JITServer should now be functional on Z. I have updated the final issue with build results here: https://github.com/eclipse/openj9/pull/10688#issuecomment-699039258. 

If any new issues arise in the future, then they can be solved individually. Closing this issue.
