### ISSUE TITLE
OMRSOCK API: Implement omrsock_socket Function on Unix

### ISSUE THREAD

**Issue by caohaley** [eclipse/omr#4795]
Working on Issue: #4102
/cc @rwy0717 @babsingh @mpirvu

Omrsock functions to be implemented:
`omrsock_socket`

### Descriptions
This function creates a socket using user preferred parameters. The omrsock_socket function will require defined constants to help with user input, as all socket api has these constants. The implementation will be a function call to system socket api `socket` function.

**omrsock_socket implementations:**

1. Check that inputs are supported by our socket api. Inputs include family, socktype, protocol.
2. Create a socket.
3. Allocate memory for socket (followed by previous decisions to follow j9sock implementations for now).

**Requirements for constant definitions:**
Currently we can start by supporting some of the basic definitions that are commonly used.

Domain Family:
AF_UNSPEC (just define as 0 in our api, used for getaddrinfo)
AF_INET
AF_INET6

Socket Type:
SOCK_ANY (just define as 0 in our api, used for getaddrinfo)
SOCK_STREAM
SOCK_DGRAM

Protocol:
SOCK_DEFPROTOCOL (default to typical protocol, just define as 0 in our api)
IPPROTO_TCP
IPPROTO_UDP

### Unix Progress Tracker

- [x]  Implement omrsock_getaddrinfo_create_hints (and socket per thread buffer) PR:#4555

- [x]  Implement OMRAddrInfoNode element extraction (omrsock_getaddrinfo_length, family, socktype, protocol) Issue:#4745, PR:#4738

- [x]  Implementing omrsock_getaddrinfo Issue: #4794

- [x]  Implementing omrsock_socket (constants definition of socket types)

- [ ]  Implementing omrsock_bind and omrsock_listen

- [ ]  Implementing omrsock_connect and omrsock_accept

- [ ]  Implementing omrsock_send and receive

- [ ]  Implementing omrsock_sendto and recvfrom

- [ ]  Implementing omrsock_close

**Comment by caohaley** [comment]
## Discussion Point 
Constants Definitions for `omrsock_socket` function:

The users will need to pass in the socket family type, socket type (stream or datagram), and protocol specifications to create a socket. Socket apis has defined constants for these types, such as AF_INET, AF_INET6, SOCK_STREAM and so on. I think we will need some too, for the convenience of users.

### Possible Approach 1:
Define in `omrportsock.h` and `omrsock.h`

**Public** (in `omr/include_core/` folder):

`omrportsock.h` content:
--> pointers to structs
--> **NEW**: definitions of types of (family) (socktype) (protocol) (flags?) as integers
Ex.
#define OMRSOCK_ANY	0	/* for getaddrinfo hints, any socktype*/
#define OMRSOCK_STREAM	1	/* stream socket */
#define OMRSOCK_DGRAM	2	/* datagram socket */
to be continued...

`omrportsocktypes.h` (no changes) content:
--> definitions of structs
--> definitions of elements of structs

**Internal** (in /root/omr/port/unix_include and /root/omr/port/win32_include folder):

**NEW** file `omrsock.h` content (unix_include and win32_include):
--> definitions of types as OS_TYPE for unix and win32
Ex.
#define OS_SOCK_ANY	0
#define	OS_SOCK_STREAM	SOCK_STREAM
#define OS_SOCK_DGRAM	SOCK_DGRAM
to be continued...

`omrsock.c` (unix and win32) content:
--> **NEW** internal functions for conversion/mapping
map_addr_family_OMR_to_OS()
map_socktype_OMR_to_OS()
map_protocol_family_OMR_to_OS()

Example implementation of map_socktype_OMR_to_OS:
```
static int32_t
map_socktype_OMR_to_OS(int32_t socktype) {
	switch(socktype){
		case OMRSOCK_ANY:
			return OS_SOCK_ANY;
		case OMRSOCK_STREAM:
			return OS_SOCK_STREAM;
		case OMRSOCK_DGRAM:
			return OS_SOCK_DGRAM;
	}
	return Error;
}
```

This approach matches j9sock implementation.
j9sock functions:
map_addr_family_J9_to_OS
map_socktype_J9_to_OS
map_protocol_family_J9_to_OS

**Comment by caohaley** [comment]
### Possible Approach 2

Define in `omrportsocktypes.h`

In this way, I was thinking of defining the types like how these were defined:
```
#if defined(OMR_OS_WINDOWS)
typedef SOCKET omr_os_socket;
typedef struct sockaddr_storage omr_os_sockaddr_storage; /* For IPv4 or IPv6 addresses */
typedef struct addrinfoW omr_os_addrinfo;  /* addrinfo structure – Unicode, for IPv4 or IPv6 */
#else /* defined(OMR_OS_WINDOWS) */
typedef int omr_os_socket;
typedef struct sockaddr_storage omr_os_sockaddr_storage; /* For IPv4 or IPv6 addresses */
typedef struct addrinfo omr_os_addrinfo; /* addrinfo structure for IPv4 or IPv6*/
#endif /* defined(OMR_OS_WINDOWS) */
```

We would do it in `omrportsocktypes.h`:
--> definitions of elements of structs
--> definitions of structs
--> **NEW** definitions of types depending on operating systems:
Ex.
```
/* Same for all operating systems (Most of them are the same) */
#define OMRSOCK_ANY	0
#define	OMRSOCK_STREAM	SOCK_STREAM
#define OMRSOCK_DGRAM	SOCK_DGRAM
...

#if defined(OMR_OS_WINDOWS)
/* Additional definitions specific to windows */
#endif /* defined(OMR_OS_WINDOWS) */
```
Approach 1 has better isolation (code from users) and organization but approach 2 requires less code to implement.

**Comment by babsingh** [comment]
+1 for **Approach 2**. Less code == simpler implementation, which is easier to maintain. I feel that the new macros (types) won't have a negative impact on the user so we don't need to isolate them. @caohaley you will need to verify the impact of exposing the new macros to the user. if there is no negative impact such as compilation errors, my suggestion is to move forward with **Approach 2**.

**Comment by rwy0717** [comment]
I'm not so sure about A2. If I understand the plan, in A2 we define the flags required by the `omrsock_socket` call in `omrportsocktypes.h`.

We introduced `omrportsocktypes.h` to isolate users from how omrsock structures are defined. These struct definitions use system headers, which caused compilation issues in J9. We've structured our code so users doesn't have to include `omrportsocktypes.h` to call omrsock APIs.

If we put these flags into `omrportsocktypes.h`, aren't we right back to where we started? Users will _have_ to include `omrportsocktypes.h` in order to call `omrsock_socket`, which will expose how our structs are defined.

**Comment by babsingh** [comment]
@rwy0717's correct, we don't want users to include `omrportsocktypes.h` (internal) for consuming the API. @caohaley may be try A2 with the types defined in `omrportsock.h` (public) and minimal headers.

**Comment by rwy0717** [comment]
Agreed, I really dislike those converters. If it's any consolation, they are probably just converting 0->0, 1->1, etc, and will be optimized away.

I suspect it won't be possible to define these constants in `omrportsock.h`, because on win32 many socket constants (for example, `SOCK_STREAM`) come from `winsock2.h`[1]. I believe this header was responsible for some of the compilation issues in J9.

1: https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-socket

**Comment by rwy0717** [comment]
If we want to be sneaky, we can define our constants to be the same values as the winsock equivalent, without actually using the winsock constants.

EG
```c++
#if defined(OMR_OS_WINDOWS)
#define OMRSOCK_STREAM 1
#define OMRSOCK_DGRAM  2
// etc...
#endif
```

And then write a test to ensure our constants match up:
```c++
#if defined(OMR_OS_WINDOWS)

#include <winsock2.h>

TEST(OmrSockTest, SockConstsMatchOsEquivalents)
{
  EXPECT_EQ(OMRSOCK_STREAM, SOCK_STREAM);
  EXPECT_EQ(OMRSOCK_DGRAM, SOCK_DGRAM);
  // etc...
}

#endif
```

**Comment by babsingh** [comment]
It's very unlikely; but, there is a possibility that the winsock constant values may change, which will break our implementation. At this point, A1 looks like an ideal approach.

**Comment by caohaley** [comment]
I will open 2 separate PRs for this Issue:
1. Define OMRSOCK constants for users to use when calling the omrsock_socket function. (Update previous code to accept the constants).
2. The implementation of omrsock_socket and related tests.

**Comment by caohaley** [comment]
@rwy0717 I have uploaded the two PRs that I've mentioned above. The second one is dependent on the first one, which is dependent on the getaddrinfo PR (#4832). If you have time today, could you take a look at them today and see if there are anything that you would like me to change?
