### ISSUE TITLE
OMRSOCK API: Implement omrsock_bind and omrsock_listen functions on Unix

### ISSUE THREAD

**Issue by caohaley** [eclipse/omr#4919]
Working on Issue: #4102
/cc @rwy0717 @babsingh @mpirvu

Omrsock functions to be implemented:
`omrsock_bind`, `omrsock_listen`

### Descriptions
`omrsock_bind` binds socket address information to a socket descriptor. This function should be called before `omrsock_listen` because `omrsock_bind` allows the socket to attach to a port number on an address, and this will be the one that the clients will be looking to connect to.

`omrsock_listen` tells the socket descriptor that it is ready to start listening for connection requests from the client.

### Implementation Details:
omrsock_bind has the function prototype:
```
omrsock_bind(struct OMRPortLibrary *portLibrary, omrsock_socket_t sock, omrsock_sockaddr_t addr);
```

One of the parameters that `omrsock_bind` needs is omrsock_sockaddr_t. Right now, we don't have any functions that allows the users to create the socket addresses and fill in its elements. Therefore, we will be needing **2 PRs** for this issue.

##### First PR
The first PR will set up the socket address parameters needed by the users. In this PR, the users will be calling a new function, that will be added to the Port Library, that allows the user to create a custom socket address.

The users will be finally using these definitions that we have already implemented.

_In omrportsock.h:_
`typedef struct OMRSockAddrStorage *omrsock_sockaddr_t;`

_and in omrportsocktypes.h:_
```
/**
 * A struct for storing socket address information. Big enough to store IPv4 and IPv6 addresses.
 */
typedef struct OMRSockAddrStorage {
	omr_os_sockaddr_storage data;
} OMRSockAddrStorage;
```
The objective of the first PR is to fill in `omr_os_sockaddr_storage` in the way that the users intends it to be. I will describe this in more details in the comment section.

##### Second PR
The second PR will be more straightforward. It will be simply the implementations of `omrsock_bind` and `omrsock_listen`. This will be as usual; just calling the system socket API functions bind() and listen(). There will be tests for these functions as well. By the end of the second PR, we should be able to implement a functional server, that can listen to requests using the OMRSOCK API. 

### Unix Progress Tracker

- [x]  Implement omrsock_getaddrinfo_create_hints (and socket per thread buffer). PR:#4555

- [x]  Implement OMRAddrInfoNode element extraction (omrsock_getaddrinfo_length, family, socktype, protocol). Issue:#4745, PR:#4738

- [x]  Implementing omrsock_getaddrinfo. Issue:#4794 PR:#4832

- [x]  Implementing omrsock_socket (constants definition of socket types) and omrsock_close. Issue:#4795 PRs:#4878, #4887 

- [x]  Implementing omrsock_bind and omrsock_listen

- [ ]  Implementing omrsock_connect and omrsock_accept

- [ ]  Implementing omrsock_send and receive

- [ ]  Implementing omrsock_sendto and recvfrom

**Comment by caohaley** [comment]
## PR 1 Details/Proposal:

 **socket address variables** 
| System socket API | Description of Use | j9sock implementations | Proposed omrsock implementation |
|---|---|---|---|
| struct sockaddr | Use this for bind(), connect(), etc. because these functions take this as a parameter. You cast sockaddr_in, sockaddr_in6, or sockaddr_storage to this when passing into these functions without worries. | [typedef struct sockaddr OSADDR;](https://github.com/eclipse/openj9/blob/e8215634090734f30ba084a83089b58dbe579a3b/runtime/port/unix_include/j9sock.h#L91) | Add definition called `omr_os_addr` |
| struct sockaddr_in | For users when they create an IPv4 AF_INET socket. Users can directly modify information such as sin_family, sin_port, sin_addr, etc. | [j9sockaddr_struct](https://github.com/eclipse/openj9/blob/0133ba037e79ad7ff4d34a0bcbc70a919a33b852/runtime/oti/portsock.h#L116), [j9sock_sockaddr_init()](https://github.com/eclipse/openj9/blob/0133ba037e79ad7ff4d34a0bcbc70a919a33b852/runtime/port/unix/j9sock.c#L3369) | Add function and implementation `omrsock_sockaddr_init()` |
| struct sockaddr_in6 | For users when they create an IPv6 AF_INET6 socket. User can directly modify information such as sin6_family, sin6_port, sin6_addr, sin6_scope_id, etc. Takes bigger space in memory than sockaddr_in. | [j9sockaddr_struct](https://github.com/eclipse/openj9/blob/0133ba037e79ad7ff4d34a0bcbc70a919a33b852/runtime/oti/portsock.h#L116), [j9sock_sockaddr_init6()](https://github.com/eclipse/openj9/blob/0133ba037e79ad7ff4d34a0bcbc70a919a33b852/runtime/port/unix/j9sock.c#L3381) | Add function and implementation `omrsock_sockaddr_init6()` |
| sockaddr_storage |  Fits either sockaddr_in and sockaddr_in6 | [OSSOCKADDR_STORAGE](https://github.com/eclipse/openj9/blob/0133ba037e79ad7ff4d34a0bcbc70a919a33b852/runtime/oti/portsock.h#L98) | We already have a definition for this. No additional implemented needed. | 

**Description of the above mentioned j9sock implementations:**

_j9sock_sockaddr_init():_ 
```
j9sock_sockaddr_init(struct J9PortLibrary *portLibrary, j9sockaddr_t handle, int16_t family, uint32_t ipAddrNetworkOrder, uint16_t portNetworkOrder)
```
- Returns handle, which is a pointer to j9sockaddr struct. User **preallocate** j9sockaddr struct.
- Cast j9sockaddr, which is sockaddr_storage, to sockaddr_in. Fills in sin_family, sin_addr.s_addr, sin_port as if j9sockaddr was sockaddr_in to begin with.

_j9sock_sockaddr_init6():_
```
j9sock_sockaddr_init6(struct J9PortLibrary *portLibrary, j9sockaddr_t handle, uint8_t *addr, int32_t addrlength, int16_t family, uint16_t portNetworkOrder,uint32_t flowinfo, uint32_t scope_id, j9socket_t sock)
```
- User **preallocate** j9sockaddr struct.
- Allows for both IPv4 address using IPv6 address (good for dual stack socket, which may be very beneficial for JIT Server team in the future), and for normal IPv6 address.
- Fills in as sockaddr_in if the family parameter is AF_INET and fills in as sockaddr_in6 if otherwise, which means it fills in sin6_family, sin6_port, sin6_addr, sin6_scope_id.



### OMRSOCK API Implementations: 

I think we should mostly focus on these 2 functions above that are mentioned. This will allow the users to create the socket address. I think other than taking out the `hostent` part of the implementation, we can keep the rest of the implementation.

One other function that we may need is `omrsock_getaddrinfo_address`. The _j9sock_getaddrinfo_address()_ is:
```
j9sock_getaddrinfo_address(struct J9PortLibrary *portLibrary, j9addrinfo_t handle, uint8_t *address, int index, uint32_t* scope_id)
```
- Returns address in a **preallocated** buffer. Address returned will be 4 or 16 bytes depending on if it is IPv4 or Ipv6. Returns scope_id if IPv6 address.
- Users need to call j9sock_getaddrinfo_family beforehand to know if it is a 4 or 16 bytes address, so they can allocate space for it accordingly. 
- Rest of the code in this function is the same as if this was other element extraction.





**Other j9sock address related functions, but not planning to implement right now:** 

_j9sock_sockaddr_family():_

```
j9sock_sockaddr_family(struct J9PortLibrary *portLibrary, int16_t *family, j9sockaddr_t handle)
```
- Answers family type by storing a family element in j9sockaddr. Pass in pointer to j9sockaddr. Kind of like element extraction of the j9sock socket address struct.

_j9sock_sockaddr_address():_

```
j9sock_sockaddr_address(struct J9PortLibrary *portLibrary, j9sockaddr_t handle):
```

- Answer the address using pointer to j9sockaddr struct. Kind of like element extraction of the j9sock socket address struct.

_j9sock_sockaddr_address6():_
```
j9sock_sockaddr_address6(struct J9PortLibrary *portLibrary, j9sockaddr_t handle, uint8_t *address, uint32_t *length, uint32_t* scope_id):
```

- Returns the IPv4 or IPv6 address in network byte order, as well as returning relevant parameters such as length and scope_id if IPv6.
- Gives option of IPv4 or IPv6, I think, to give flexibility in creating a dual stack socket.

_j9sock_sockaddr():_
```
j9sock_sockaddr(struct J9PortLibrary *portLibrary, j9sockaddr_t handle, const char *addrStr, uint16_t portNetworkOrder)
```

- Related to hostent so not planning to implement/include in omrsock.
- Not completely sure what it does but seems like it tries to find an address and call sockaddr_init with it. Contains deprecated function gethostbyname.
