### ISSUE TITLE
OMRSOCK API: Implement omrsock_connect and omrsock_accept functions on Unix 

### ISSUE THREAD

**Issue by caohaley** [eclipse/omr#5043]
Working on Issue: #4102
/cc @rwy0717 @mpirvu

Omrsock functions to be implemented:
`omrsock_connect`, `omrsock_accept`

### Descriptions
`omrsock_connect` is usually called by the client that wishes to connect to a server.
If the initiating socket is for datagram connections, `omrsock_connect` will set up peer address but no connection is actually made. When peer address is set, this datagram socket will be only for sending and receiving from the peer address. The peer can be switched with consecutive calls to `omrsock_connect` and can be disconnected from the peer with a call to `omrsock_connect` with NULL address.
If the initiating socket is for stream connection, `omrsock_connect` will attempt to establish a connection with the server address passed in. It will attempt to connect for a time interval and either fail or succeed. The nonblock functionality will be implemented and added in the future.

`omrsock_accept` is called to accept the first connection in the queue of pending connections. It will then return a new socket specifically for that connection.

### Implementation Details:
The `omrsock_connect` function will be set up to call the system socket api connect function. It will be tested to see if it works on all Unix systems and if there is anything to be added.

The `omrsock_accept` function will call the system socket api accept function and will allocate memory for a new `OMRSocket` structure for the newly returned socket descriptor for the connection. This socket structure will be released when the user calls `omrsock_close` to close the socket. It is the user's responsibility to close the sockets at the end of their program.

### Unix Progress Tracker
- [x]  Implement omrsock_getaddrinfo_create_hints (and socket per thread buffer). PR:#4555

- [x]  Implement OMRAddrInfoNode element extraction (omrsock_getaddrinfo_length, family, socktype, protocol). Issue:#4745, PR:#4738

- [x]  Implementing omrsock_getaddrinfo. Issue:#4794 PR:#4832

- [x]  Implementing omrsock_socket (constants definition of socket types) and omrsock_close. Issue:#4795 PRs:#4878, #4887

- [x]  Implementing omrsock_bind and omrsock_listen Issue:#4919 PRs:#4974, #5034

- [x]  Implementing omrsock_connect and omrsock_accept

- [ ]  Implementing omrsock_send and receive

- [ ]  Implementing omrsock_sendto and recvfrom
