### ISSUE TITLE
OMRSOCK API: Implementing omrsock_setsockopt and omrsock_getsockopt functions on Unix

### ISSUE THREAD

**Issue by caohaley** [eclipse/omr#5158]
Working on Issue: #4102
/cc @rwy0717 @mpirvu

The  minimal socket api for Unix is done being implemented and is currently waiting to be merged. However, these functions need to be added for the JITServer team functionalities and will be the last functions to be implemented.

Omrsock functions to be implemented:
`omrsock_setsockopt_int`, `omrsock_setsockopt_linger`, `j9sock_linger_init`, `omrsock_setsockopt_timeval`, `j9sock_timeval_init`

`omrsock_getsockopt_int`, `omrsock_getsockopt_linger`, `omrsock_getsockopt_timeval`

### Descriptions
`setsockopt` basically configures the socket options at a specifed level, usually at the socket level `SOL_SOCKET` but could be different depending on what option you set. The function prototype for  system`setsockopt` is:
```
int setsockopt(int s, int optionLevel, int optionName, const void *optionValue, socklen_t optionLength);
```
Depending on the option you set, it may belong to a different option level, and may require you to input a specific value type, such as a pointer to integer, boolean, `linger struct`, `timeval struct` and so on (thus it takes in a `void *`), and have you specify the length.

`getsockopt` essentially does the opposite where the users pass in a preallocated buffer and the function call fills in the buffer with the current configuration of the socket for that option. The function prototype for  system`getsockopt` is:
```
int getsockopt(int s, int level, int optname, void *optval, socklen_t *optlen);
```

### Implementation Details:

The options that will be supported first will be the ones that JITServer currently uses in the code including:
- SO_REUSEADDR
- SO_KEEPALIVE
- SO_LINGER
- SO_RCVTIMEO
- SO_SNDTIMEO
- TCP_NODELAY

We will introduce two new data types in `omrportsocktypes.h`:
- struct omrsock_timeval that contains `struct timeval`
and
- struct omrsock_linger that contains `struct linger`

We will also introduce two corresponding init functions: `j9sock_timeval_init` and `j9sock_linger_init` to fill in the value of these two option values.

Because of the user isolation and they can not directly modify the option values, we will need to implement three different functions rather than the one in system socket api. We will separate the option value types into integer, struct timeval and struct linger.

Thus, there will be a different function call for each of the different option types: `omrsock_setsockopt_int`, `omrsock_setsockopt_linger`, `omrsock_setsockopt_timeval`.

However, all three functions will be just set up to call the system socket api setsockopt and getsockopt functions. It will be tested to see if it works on all Unix systems and if there is anything to be added.

### Unix Progress Tracker
- [x]  Implement omrsock_getaddrinfo_create_hints (and socket per thread buffer). PR:#4555
- [x]  Implement OMRAddrInfoNode element extraction (omrsock_getaddrinfo_length, family, socktype, protocol). Issue:#4745, PR:#4738
- [x]  Implementing omrsock_getaddrinfo. Issue:#4794 PR:#4832
- [x]  Implementing omrsock_socket (constants definition of socket types) and omrsock_close. Issue:#4795 PRs:#4878, #4887
- [x]  Implementing omrsock_bind and omrsock_listen Issue:#4919 PRs:#4974, #5034
- [x]  Implementing omrsock_connect and omrsock_accept Issue:#5043 PR:#5066
- [x]  Implementing omrsock_send and receive Issue:#5069 PR:#5124
- [x]  Implementing omrsock_sendto and recvfrom Issue:#5128 PR:#5139
- [x] Implementing omrsock_setsockopt and omrsock_getsockopt functions
