### ISSUE TITLE
Roadmap for adopting changes in OMR AOT Compiler infrastructure

### ISSUE THREAD

**Issue by georgkrylov** [eclipse/omr#5469]
This issue presents a list of future work steps that need to be done to adopt code introduced in #4557, originally described in #4556
The work items presented here mostly do not depend on each other and the order of ticking off the check marks is not fixed.

- [ ] Review and merge #5244, that provides basic functional verification
- [ ] Settle on external API for #5119, that would allow integrating OMR AOT with Jitbuilder as a seamless option
- [ ] Resolve problems related to autoconf failures that require changes to OpenJ9 makefiles
Those changes include
* Renaming TRRelocationRecord TRRelocationRuntime and TRRelocationTarget
* Turning  corresponding OpenJ9 files to be parts of extensible classes hierarchy
* In base classes AheadOfTimeCompile
- [ ] Have a discussion about memory for AOTMethodHeader
- [ ] Rewire RelocationRecord sizes to use class member variables instead of _relocationKindToHeaderSizeMap, _relocationKindToHeaderSizeMap could be gone then
- [ ] Extending RelocationRecordBinaryTemplates should be done with [these guidelines](https://github.com/eclipse/omr/pull/4557#discussion_r355065778) in mind.
- [ ] Finding a better solution for calling for a project specific relocations, the problem is described [here](https://github.com/eclipse/omr/pull/4557#discussion_r355078632)
- [ ] Think on infrastructure for better relocation creation during the code generator (instructions phase), that might remove the need to modify OMR files when extended by other projects
- [ ] A further improvement to BinaryTemplates is suggested [here](https://github.com/eclipse/omr/pull/4557#issuecomment-564096729)
- [ ] If RelocationRecord, RelocationTarget and ReloRuntime are used in OpenJ9, several methods should have the ```virtual``` keyword removed, since static polymorphism replaces dynamic dispatch in this case
- [ ] This [code](https://github.com/eclipse/omr/pull/4557/files#diff-bc0d22383647c90b686810e3bdd23a3bR240-R243) Should be unified. (currently AheadOfTimeCompile is not generated in OMR, instead, it is generated in downstream in OpenJ9)
- [ ] The ExternalRelocation->apply might need a discussion to have its method renamed, as discussed [here](https://github.com/eclipse/omr/pull/4557/files#r395597914)
- [ ] The code for querying the size of RelocationRecord needs to be updated if OpenJ9 relocations adapt OMR relocations [illustrative example](https://github.com/eclipse/omr/pull/4557/files#diff-0fed9f5d8b4290a9bf56682d3dcf7885R567-R571)
- [ ] [This function](https://github.com/eclipse/openj9/blob/66a63178ffcac4dd34eb6747c2e4e55efb878dd6/runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp#L844) can be renamed to have a more appropriate name
- [ ] Address usage of const char* instead of ResolvedMethod as indicated [here](https://github.com/eclipse/omr/pull/4557#pullrequestreview-408287289) and continued [here](https://github.com/eclipse/omr/pull/4557#discussion_r461243248)
- [ ] Resolve problem of missing symbols when compiling for OpenJ9 with cmake and autoconf to not have [function names like this](https://github.com/eclipse/omr/pull/4557/files#diff-03b8aa223d7e803d9246f52fc482f19cR133).
- [ ] Address access modifier in AheadOfTimeCompile for methods, as discussed [here](https://github.com/eclipse/omr/pull/4557#discussion_r461268655)

This list is not final and might grow with upcoming reviews
The discussion is encouraged and welcomed!
